package com.test.shopping.entity;

public class Specval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specval.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specval.specid
     *
     * @mbg.generated
     */
    private Integer specid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specval.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specval.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specval.id
     *
     * @return the value of specval.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specval.id
     *
     * @param id the value for specval.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specval.specid
     *
     * @return the value of specval.specid
     *
     * @mbg.generated
     */
    public Integer getSpecid() {
        return specid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specval.specid
     *
     * @param specid the value for specval.specid
     *
     * @mbg.generated
     */
    public void setSpecid(Integer specid) {
        this.specid = specid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specval.value
     *
     * @return the value of specval.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specval.value
     *
     * @param value the value for specval.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specval.sort
     *
     * @return the value of specval.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specval.sort
     *
     * @param sort the value for specval.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}